### ISSUE TITLE
Upgrade to swift 5

### ISSUE THREAD

**Issue by hoangtaiki** [BiAtoms/Http.swift#14]
@OrkhanAlikhanov Do we have plan for upgrading 5?
I also see we specify Xcode9.3 in .travis.yml. I think it is too old.

**Comment by OrkhanAlikhanov** [comment]
Will try this weekend, thank you!

**Comment by OrkhanAlikhanov** [comment]
Upgraded it, you can find it at [v2.2.0](https://github.com/BiAtoms/Http.swift/releases/tag/2.2.0), commit https://github.com/BiAtoms/Http.swift/commit/440a6dcbcaf6708b777122294714482f6b159c99
