### ISSUE TITLE
Multipart Requests

### ISSUE THREAD

**Issue by mdidon** [BiAtoms/Http.swift#18]
Is it possible to call multipart requests (i.e. file upload) using this library?

Thanks

**Comment by OrkhanAlikhanov** [comment]
Not by simple means. But I think you can do it by setting response content type header and sending raw bytes as body. A general form of [multipart requests](https://swagger.io/docs/specification/describing-request-body/multipart-requests/)
```http
POST /upload HTTP/1.1
Content-Length: 428
Content-Type: multipart/form-data; boundary=abcde12345
--abcde12345
Content-Disposition: form-data; name="address"
Content-Type: application/json
{
  "street": "3, Garden St",
  "city": "Hillsbery, UT"
}
--abcde12345
Content-Disposition: form-data; name="profileImage "; filename="image1.png"
Content-Type: application/octet-stream
{…file content…}
--abcde12345--
```

**Comment by mdidon** [comment]
@OrkhanAlikhanov Not to worry, looks like this method works.
Thanks
