### ISSUE TITLE
Run on Device

### ISSUE THREAD

**Issue by sergeymild** [BiAtoms/Http.swift#2]
Hi, trying run server on Iphone device (not emulator) and go to http://localhost:8080 in browser but it's not working.

**Comment by OrkhanAlikhanov** [comment]
`localhost` needs to be replaced with the ip address of your phone, where your phone and pc is on the same network.

**Comment by OrkhanAlikhanov** [comment]
Oh, you go to `localhost:8080` in your phone?

**Comment by sergeymild** [comment]
oh, sorry, my fault, all working with ip address, thanks

**Comment by OrkhanAlikhanov** [comment]
So, I am closing the issue. Thank you!

**Comment by OrkhanAlikhanov** [comment]
Hey, if you have some quick questions you can ask them here at [gitter](https://gitter.im/BiAtoms/Http.swift).
