### ISSUE TITLE
Carthage?

### ISSUE THREAD

**Issue by jeff-h** [BiAtoms/Http.swift#3]
Any chance you'd add Carthage support? This library deserves wider recognition :)

**Comment by OrkhanAlikhanov** [comment]
Hey, thank you :) I'll try to add. It seems I need to add Carthage support for the dependencies firstly. Stay tuned 👍

**Comment by OrkhanAlikhanov** [comment]
Hey @jeff-h! Sorry for my very late action to this request. I finally added carthage support as of version 2.1.1! Any feedback is appreciated. Thank you!
```
github "BiAtoms/Http.swift" ~> 2.1
```

**Comment by jeff-h** [comment]
Fantastic, thanks! I will let you know how it goes in my project :)

**Comment by OrkhanAlikhanov** [comment]
Awesome. Thank you for the feedback. I really appreciate!
