### ISSUE TITLE
SSL / TLS?

### ISSUE THREAD

**Issue by jeff-h** [BiAtoms/Http.swift#4]
I'm using this to serve some stuff which my app then displays in a WKWebView. Given that Apple really want us using https, is SSL / TLS on your radar? I see you recently added it in the sockets dependency, so I'm hopeful :)

**Comment by OrkhanAlikhanov** [comment]
I think adding SSL support would be easy considering that Socket.swift has it. Actually once I had thought adding it, then I decided I'll add it on demand. So since you are in need, I'll add it :) Unfortunately I am and will be really really busy these days. Probably I can do it at the next weekend. Thank you for your interest :)

**Comment by jeff-h** [comment]
Wow, thanks! Love how much cleaner your code is than a certain highly-starred similar project... :see_no_evil:

**Comment by OrkhanAlikhanov** [comment]
Thank you for your appreciation :)

**Comment by jeff-h** [comment]
This is awesome! Can't wait to try it out :)

**Comment by OrkhanAlikhanov** [comment]
Hey! I thought I had left a comment here after closing via https://github.com/BiAtoms/Http.swift/commit/1d1e26835cb10c46299022be5d9fb1eca33943e9 . Seems that I hadn't. Sorry for that. You can reach [me at gitter](https://gitter.im/OrkhanAlikhanov) if you want to discuss something about `Http.swift`

**Comment by jeff-h** [comment]
Will definitely drop in and say hi on Gitter!

I found it a bit tricky to get this to build. Since I use Carthage in my project, I'm building this separately using the workspace included with this project to build the two frameworks I need (Http.swift and Sockets.swift). But running `pod install` on a fresh checkout of this repo just kept installing v2.1.0 of Sockets.swift, not the newly-required v2.2.0. 

In the end I got it working by modifying the `Podfile` like so:

```
  # Pods for HttpSwift
  pod 'Socket.swift', :git => 'https://github.com/BiAtoms/Socket.swift.git', :branch => 'master', :tag => '2.2.0'
```

I'm guessing my problems are almost certainly due to my lack of understanding Cocoapods, but I mention it here in case there's some tiny config error somewhere in the project or on Cocoapods.org or something.

**Comment by OrkhanAlikhanov** [comment]
The build is passing in travis ci, so I am sure about my side. Your pod repo might be out of date. Remove `:git => ...` stuff and try `pod install --repo-update` it should work. As regards the carthage, it's in my queue ;)

**Comment by jeff-h** [comment]
You're right — thanks a lot! The `--repo-update` was key... it builds just fine now.
