### ISSUE TITLE
Playing .mp4 encrypted video

### ISSUE THREAD

**Issue by payalbaldota** [BiAtoms/Http.swift#5]
Hi,
Can I use this framework to play encrypted video file (.mp4) using AVPlayer?

I will be running local HTTP server for this.

Regards,
Payal

**Comment by OrkhanAlikhanov** [comment]
Hey! I didn't get what you mean thoroughly, but let me go through it :)
1. I think you mean .mp4 encoded video not encrypted.  
2. If you want to play just an mp4 video file via AVPlayer, you don't need an HTTP server. Just give url to that local .mp4 file.
3. I think for streaming a video, server needs to respect [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) which this server does not

**Comment by OrkhanAlikhanov** [comment]
Hey, I haven't heard back from you. I am closing the issue. Feel free to reopen if needed
