### ISSUE TITLE
How to use Http.Swift

### ISSUE THREAD

**Issue by qBor** [BiAtoms/Http.swift#7]
hi, i have installed your Framework, now I tried to C/P your readme `let server = Server()
server.get("/hello/{id}") { request in
    print(request.queryParams["state"])
    return .ok(request.routeParams["id"]!) 
}

try server.run()`

but I have an error on server.run  : "Error thrown from here are not handled"

**Comment by qBor** [comment]
and a second question, how to use a certain port and can I use server.stop or similar to stop server?

**Comment by qBor** [comment]
Thanks for your reply

**Comment by OrkhanAlikhanov** [comment]
Forgot to mention, to run server on different port you can do `try! server.run(port: 4443)`
