### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by jeff-h** [BiAtoms/Http.swift#8]
I think there may be a retain cycle here:

https://github.com/BiAtoms/Http.swift/blob/1d261d012b525a82ca8e26e78afa85324b921393/Sources/Server.swift#L42-L47

I think it should be:

```swift
        queue.async { [weak self] in
            guard let self = self else {return}
            while let client = try? self.socket.accept() { 
                self.handleConnection(client) 
                client.close() 
            } 
        } 
```

What do you think?

**Comment by OrkhanAlikhanov** [comment]
`DispatchQueue`s does not cause retain cycles, they dispose passed closure after calling them.

However, there is a bigger problem here even. Calling `server.stop()` does not seem to stop the `while` loop in the snipped above. To be honest, the library needs a total rewrite.

**Comment by OrkhanAlikhanov** [comment]
Thank you for your care!

**Comment by OrkhanAlikhanov** [comment]
Hey! Thank you for your care!

`DispatchQueue`s does not cause retain cycles, they dispose passed closure after calling them, meaning they do not retain reference to the closure passed.

To be honest, the library needs a total rewrite.

**Comment by jeff-h** [comment]
Hi — thanks for your explanation. So if I can't blame my leak on your code I will have to fix mine lol

**Comment by jeff-h** [comment]
Oh man. Over time my code potentially opens and closes quite a few `Server`s, one after the other, and they were retaining just because I forgot to call `.stop()` on them when I was finished with each instance 🤪 Spent such a long time searching for the cause of this leak!

Interesting, I suppose, that the `Server` instances appear to self-retain until stopped, but it's kinda obvious when I think about it. Anyway, definitely my fault in the end!

**Comment by OrkhanAlikhanov** [comment]
Lol. Yeah they will retain until stopped because of missing [weak self] in the queue closure that you wanted to add. I think it would be better to do it. Would you like to send a quick PR for that?

**Comment by jeff-h** [comment]
Sure, doing now :)
